# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [test-ci-cd]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          mkdir dev
          echo "$ENV_FILE" > ./dev/.env
          cat ./dev/.env

        # shell: bash
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

        # env: # Or as an environment variable
        #   PORT: ${{ secrets.PORT }}
        #   MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        #   REDIS_HOST: ${{ secrets.REDIS_HOST }}
        #   ENV_FILE: ${{ secrets.ENV_FILE }}
      # - run: echo "::set-env name=PORT::8000"
      # - run: echo "::set-env name=MONGODB_CONNECTION_STRING::mongodb://localhost:27017/test"
      # - run: echo "::set-env name=REDIS_HOST::${{ secrets.REDIS_HOST }}"

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ci_test
      - name: Create .ssh files
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          'which ssh-agent || ( apk update && apk add openssh-client )'
          'which curl || apk add curl'
          eval $(ssh-agent -s)
          echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        shell: bash
        env:
          CI: true
